apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data
  labels:
    k8s-app: sql-server
spec:
  storageClassName: rook-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
