kind: Job
apiVersion: batch/v1
metadata:
  name: deploy-glidergun-remote
spec:
  completions: 1
  template:
    metadata:
      name: deploy-glidergun-remote
    spec:
      containers:
      - name: deploy-glidergun-remote
        image: ddresearch.azurecr.io/glidergun/remote/node:latest
        env:
          - name: TF_VAR_dns_subdomain
            value: yo-dawg
          - name: TF_VAR_ssh_key_file
            value: /secrets/id_rsa
          - name: TF_VAR_ssh_public_key_file
            value: /secrets/id_rsa.pub
        volumeMounts:
          - name: state
            mountPath: /state
          - name: ssh-key
            mountPath: /secrets/id_rsa

      # Time out after 20 minutes.
      activeDeadlineSeconds: 1200

      # Do not restart containers after they exit
      restartPolicy: Never

      volumes:
        - name: state
          hostPath:
            path: /var/run/glidergun/state
            type: Directory

        - name: ssh-key
          hostPath:
            path: /etc/glidergun/keys/ssh
            type: File
